stages:
  - serverConnection
  - test
  - build
  - deploy

#test Connection with server
testServer:
  stage: serverConnection
  before_script:
    - echo "action before script"
    - chmod 400 $RSA
  script:
    - ssh -o StrictHostKeyChecking=no -i $RSA "$VM_USER@$VM"
    - echo "success"
  
#run all units tests
run_tests:
  stage: test
  before_script:
    - echo "action before script"
  script:
    - echo "make test..."


#build application image by docker compose
build_image:
  stage: build
  before_script:
    - echo "action before script"
  script:
    - echo "build image..."

#deploy application to server
deploy:
  stage: deploy
  before_script:
    - echo "action before script"
  script:
    - echo "deploy app..."
