variables:
  IMAGE_NAME: ZeangGao/demo-app
  IMAGE_TAG: team-project

stages:
  - test
  - checkDB
  - build
  - deploy

#run all units tests
run_tests:
  stage: test
  script:
    - echo "make test"

#check DB connection
check_DB_connection:
  stage: checkDB
  before_script:
    - chmod 400 $RSA
  script:
    - ssh -o StrictHostKeyChecking=no -i $RSA "$VM_USER@$VM"
    - echo "check docker ps ..."

#build application image by docker compose
build_image:
  stage: build
  script:
    - echo "build image"

#deploy application to server
deploy:
  stage: checkDB
  script:
    - echo "deploy..."
