stages:
  - test
  - DBConnection
  - build
  - deploy

  
#run all units tests
run_tests:
  stage: test
  before_script:
    - echo "action before script"
  script:
    - echo "make test..."

#check DB connection
check_DB:
  stage: DBConnection
  before_script:
    - echo "action before script"
    - chmod 400 $RSA
  script:
    - ssh -o StrictHostKeyChecking=no -i $RSA "$VM_USER@$VM"
    - echo "docker ps"

#build application image by docker compose
build_image:
  stage: build
  before_script:
    - echo "action before script"
  script:
    - echo "build image..."

#deploy application to server
deploy:
  stage: deploy
  before_script:
    - echo "action before script"
  script:
    - echo "deploy application..."
