# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  teamproject-app:
    image: teamproject
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://teamproject-postgresql:5432/teamproject
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://teamproject-postgresql:5432/teamproject
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  teamproject-postgresql:
    image: postgres:14.5
    volumes:
      - ~/volumes/jhipster/teamproject/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=teamproject
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 127.0.0.1:5432:5432
